name = "mletras-auth-api"
main = "src/index.ts"
compatibility_date = "2024-01-15"
compatibility_flags = ["nodejs_compat"]

# D1 Database for users, OTPs, usage tracking
[[d1_databases]]
binding = "DB"
database_name = "mletras-auth-db"
database_id = "5a258f07-dc5a-4f3b-b92d-8616babb8ec8"

# KV for session storage and rate limiting
[[kv_namespaces]]
binding = "SESSIONS"
id = "3936670d62734e6e9cab014bd0d50653"

# Durable Objects for per-user burst limiting (will be created)
# [[durable_objects.bindings]]
# name = "RATE_LIMITER"
# class_name = "RateLimiter"

# Environment variables and configuration
[vars]
ENVIRONMENT = "production"
MUSIXMATCH_API_KEY = "4d54e92614bedfaaffcab9fdbf56cdf3"
ALLOWED_ORIGINS = "https://mletras.com,https://mletras.vercel.app,https://localhost,http://localhost,http://localhost:8080,http://localhost:8081,http://localhost:3000,http://127.0.0.1,http://127.0.0.1:8080,http://127.0.0.1:8081,http://127.0.0.1:3000,http://10.0.2.2:8080,http://10.0.2.2:3000"
FREE_DAILY_LIMIT = "100"
FREE_BURST_LIMIT = "5"
PRO_DAILY_LIMIT = "1000"
PRO_BURST_LIMIT = "20"
BURST_WINDOW_SECONDS = "60"

# Secrets (set via: wrangler secret put)
# JWT_SECRET = ""  # Generate a random 32+ character string
# EMAIL_API_KEY = "re_GWvdJLzz_L6QWWuy1xX48N6REK77vJ5y6"  # Your Resend API key

# Route configuration
routes = [
  { pattern = "auth.mletras.com/*", zone_name = "mletras.com" },
  { pattern = "api.mletras.com/*", zone_name = "mletras.com" }
]

# Development environment
[env.development]
name = "mletras-auth-api-dev"
vars = { ENVIRONMENT = "development", MUSIXMATCH_API_KEY = "4d54e92614bedfaaffcab9fdbf56cdf3", ALLOWED_ORIGINS = "https://mletras.com,https://mletras.vercel.app,https://localhost,http://localhost,http://localhost:8080,http://localhost:8081,http://localhost:3000,http://127.0.0.1,http://127.0.0.1:8080,http://127.0.0.1:8081,http://127.0.0.1:3000,http://10.0.2.2:8080,http://10.0.2.2:3000", FREE_DAILY_LIMIT = "100", FREE_BURST_LIMIT = "5", PRO_DAILY_LIMIT = "1000", PRO_BURST_LIMIT = "20", BURST_WINDOW_SECONDS = "60" }

[[env.development.d1_databases]]
binding = "DB"
database_name = "mletras-auth-db"
database_id = "5a258f07-dc5a-4f3b-b92d-8616babb8ec8"

[[env.development.kv_namespaces]]
binding = "SESSIONS"
id = "3936670d62734e6e9cab014bd0d50653"

# Production environment  
[env.production]
name = "mletras-auth-api"
vars = { ENVIRONMENT = "production" }
